apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment_service_deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment_api
  template:
    metadata:
      labels:
        app: payment_api
    spec:
      containers:
      - name: payment_api
        image: localhost:5000/payment_service_image
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
---

apiVersion: v1
kind: Service
metadata:
  name: payment_service
spec:
  selector:
    app: payment_api
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIp
